# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/local_db?serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: 123456
    url: jdbc:mysql://10.1.107.110:3306/train?serverTimezone=GMT%2B8
    username: root
    password: Aa@123456
#  session:
#    store-type: jdbc # 或者启动类加注解
#    jdbc:
#      initialize-schema: embedded # 如果使用嵌入式数据库，Spring会自动创建模式。
##      table-name:
#    timeout: 600 # 单位是秒
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
logging:
  level:
    com:
      lzf: debug


thread-pool:
  corePoolSize: 5
  maxPoolSize: 100
  queueCapacity: 2048
  keepAliveSeconds: 60
  threadNamePrefix: common-

scheduled-period: 60

smsotp:
  initialValue:
    version: 0
    lastSendOtpTimes: 0
    lastVerifyOtpTimes: 0
    codeLength: 6
  maximum:
    lastSendOtpTimes: 5
    lastVerifyOtpTimes: 3
  interval:
    sendFreezeTime: 1 # 单位：h
    sendIntervalTime: 100 # 单位：s

file-upload:
  allow-content-type: image
  local-folder-path: /secure-upload-folder/

brush:
  - 2 4 5 6 12 14 16 17 18 23 25 26 28 32 33 34 36 37 38 39 41
