# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/local_db?serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: 123456
    url: jdbc:sqlserver://10.1.107.105:1433;DataBase=practice;encrypt=true;trustServerCertificate=true
    username: sa
    password: forms123456

logging:
  level:
    com:
      lzf: debug


thread-pool:
  corePoolSize: 5
  maxPoolSize: 100
  queueCapacity: 2048
  keepAliveSeconds: 60
  threadNamePrefix: common-

scheduled-period: 60

smsotp:
  initialValue:
    version: 0
    lastSendOtpTimes: 0
    lastVerifyOtpTimes: 0
    codeLength: 6
  maximum:
    lastSendOtpTimes: 5
    lastVerifyOtpTimes: 3
  interval:
    sendFreezeTime: 1 # 单位：h
    sendIntervalTime: 100 # 单位：s

